global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-backend"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["spring-backend:8080"] # backend Spring Boot cháº¡y local

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
